version: "3.9"

services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SDPDP-beta1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sdp-net

  backend:
    container_name: springboot
    build:
      context: ./SDP-CICD-B
      dockerfile: ../SDP-FULL-STACK/backend.Dockerfile
    image: sdp-cicd-backend-b:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/SDPDP-beta1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "2222:7888"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - sdp-net

  frontend:
    container_name: react
    build:
      context: ./SDP-CICD-F
      dockerfile: ../SDP-FULL-STACK/frontend.Dockerfile
    image: sdp-cicd-frontend-f:latest
    ports:
      - "7878:80"
    depends_on:
      - backend
    networks:
      - sdp-net

volumes:
  mysql-data:

networks:
  sdp-net:
    driver: bridge
